version: '3'

services:
  db_postgres:
    container_name: 'db_order'
    image: 'postgres:12.6-alpine'
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./database/auction:/var/lib/postgresql/data/
